import { PageHero, SiteShell, type Lang } from "./SiteShell";

const data={zh:{kicker:"SELECTED WORK",title:"项目",desc:"从 RTL 与 FPGA 验证，到体系结构仿真与生成式模型压缩。所有结果仅在完成验证后量化公开。",projects:[
  ["硬件设计空间探索与 PPA 预测框架","研究项目 · 进行中","针对异构加速器设计周期较长的问题，构建从 C/C++ 源码直接预测硬件性能、功耗与面积的评估流程。",["使用 gem5 搭建多核处理器与存储系统模型，并组织硬件平台—模拟器平台 PPA 数据对。","使用 CACTI 建立缓存面积、功耗与延迟模型，形成可用于学习的 PPA 数据集。","探索微调大模型提取 C/C++ 静态特征，学习源码到硬件指标的映射。"],"gem5 · CACTI · Python · C/C++ · LLM"],
  ["数字电路设计与 FPGA 验证","工程项目 · 已完成原型","面向高性能计算模块完成 RTL 实现、综合约束、覆盖率驱动验证与 FPGA 调试。",["基于 Verilog 设计多时钟域异步 FIFO，处理跨时钟域数据传输。","使用 Design Compiler 完成逻辑综合与 SDC 约束优化。","通过 SystemVerilog 构建随机约束验证环境，并在 Xilinx FPGA 上完成时序收敛与硬件调试。"],"Verilog · SystemVerilog · Synopsys DC · FPGA"],
  ["生成式模型的 VVC 张量压缩系统","前沿研究 · 进行中","利用传统视频编码工具消除生成式模型中间特征的时空冗余，探索压缩与计算旁路的协同收益。",["离线分析 Diffusion / Transformer 中间特征图的冗余结构。","针对张量数据适配 VVenC / VVdeC，并开展编解码参数搜索。","设计计算 Bypass 机制，推进 CUDA C++ 级系统集成与端到端评估。"],"H.266/VVC · CUDA C++ · Diffusion · Profiling"]]},
  en:{kicker:"SELECTED WORK",title:"Projects",desc:"From RTL and FPGA verification to architecture simulation and generative-model compression. Quantitative results are published only after validation.",projects:[
  ["ML-driven DSE and PPA Prediction","Research · In progress","A pipeline for predicting hardware performance, power, and area directly from C/C++ source code to shorten heterogeneous-accelerator exploration cycles.",["Model multi-core processors and memory systems in gem5 and organize paired platform–simulator PPA data.","Use CACTI to model cache area, power, and latency and construct a learning-ready PPA dataset.","Explore fine-tuned language models for extracting static code features and mapping source code to hardware metrics."],"gem5 · CACTI · Python · C/C++ · LLM"],
  ["Digital Circuit Design & FPGA Verification","Engineering · Prototype complete","End-to-end RTL implementation, synthesis constraints, coverage-driven verification, timing closure, and FPGA debugging for a high-performance computing module.",["Designed a multi-clock asynchronous FIFO in Verilog for clock-domain crossing.","Performed logic synthesis and SDC constraint optimization with Design Compiler.","Built a SystemVerilog constrained-random environment and completed timing closure and debugging on Xilinx FPGA."],"Verilog · SystemVerilog · Synopsys DC · FPGA"],
  ["VVC Tensor Compression for Generative Models","Research · In progress","A system that uses video-coding tools to remove spatiotemporal redundancy in generative-model features and coordinate compression with compute bypass.",["Profile redundancy in intermediate features of diffusion and Transformer models.","Adapt tensors to VVenC / VVdeC and search codec parameters.","Design compute-bypass operators and integrate the pipeline in CUDA C++ for end-to-end evaluation."],"H.266/VVC · CUDA C++ · Diffusion · Profiling"]]}};

export function ProjectsPage({lang}:{lang:Lang}){const c=data[lang];return <SiteShell lang={lang} active="projects"><PageHero kicker={c.kicker} title={c.title} description={c.desc}/><div className="page-body"><div className="projects">{c.projects.map(([title,status,desc,points,tags],i)=><article className="project-card" key={title as string}><div className="project-index">0{i+1}</div><div><div className="status">{status as string}</div><h2>{title as string}</h2><p>{desc as string}</p><ul className="project-points">{(points as string[]).map(p=><li key={p}>{p}</li>)}</ul><div className="tag-list">{(tags as string).split(" · ").map(t=><span className="tag" key={t}>{t}</span>)}</div></div></article>)}</div></div></SiteShell>}
