import { PageHero, SiteShell, type Lang } from "./SiteShell";

const data={
  zh:{kicker:"RESEARCH",title:"研究",desc:"以可测量、可验证、可落地为原则，在生成式模型、视频编码与硬件体系结构之间建立连接。",
    intro:"我关注 AI 计算中的冗余如何被发现、编码并转化为真实的系统收益。研究跨越模型算子、压缩算法、体系结构仿真与 CUDA C++ 集成。",
    pipeline:[["冗余分析","离线 Profiling 特征图的空间、时间及通道相关性"],["张量适配","将中间特征映射为适合 VVC 编解码的数据表示"],["参数调优","围绕 VVenC / VVdeC 调整编码工具与率失真配置"],["算子旁路","设计 Bypass 机制，减少可预测或可复用的计算"],["系统评估","测量压缩率、延迟、吞吐、显存与端到端收益"]],
    heading:"核心研究方向",cards:[["AI 软硬件协同设计","面向 AI 加速器与端侧计算，从模型特征、算子行为和硬件约束共同寻找设计空间。"],["生成式模型 × 视频编码","探索 H.266/VVC 对 Diffusion、Transformer 与视频生成模型中间特征的压缩能力。"],["体系结构建模与 PPA","通过 gem5、CACTI 及综合流程建立性能、功耗与面积的多层次评估链路。"],["系统级集成与优化","以 CUDA C++、Profiling 和软硬件协同 Pipeline 将算法原型推进到可运行系统。"]],
    status:"当前课题",statusTitle:"面向生成式模型的 H.266/VVC 张量压缩与计算旁路",statusDesc:"项目处于研究与原型开发阶段。当前工作包括特征图冗余分析、VVenC/VVdeC 数据适配、编解码参数搜索、Bypass 算子设计及 CUDA C++ 集成。实验结果将在验证后公开。"},
  en:{kicker:"RESEARCH",title:"Research",desc:"Connecting generative models, video coding, and computer architecture through measurable, verifiable, and deployable systems.",
    intro:"I study how redundancy in AI computation can be discovered, encoded, and converted into real system-level gains. My work spans model operators, compression, architecture simulation, and CUDA C++ integration.",
    pipeline:[["Profile redundancy","Analyze spatial, temporal, and channel correlations in intermediate features"],["Adapt tensors","Map feature tensors to representations compatible with VVC codecs"],["Tune codecs","Configure VVenC / VVdeC tools and rate-distortion trade-offs"],["Bypass compute","Design bypass mechanisms for predictable or reusable operations"],["Evaluate systems","Measure compression, latency, throughput, memory, and end-to-end gains"]],
    heading:"Core Directions",cards:[["AI Hardware–Software Co-Design","Explore the joint design space of model characteristics, operator behavior, accelerators, and edge-computing constraints."],["Generative Models × Video Coding","Investigate H.266/VVC compression of intermediate features in diffusion, Transformer, and video-generation models."],["Architecture Modeling & PPA","Build multi-level performance, power, and area evaluation pipelines using gem5, CACTI, and synthesis flows."],["System Integration & Optimization","Turn algorithmic prototypes into runnable systems with CUDA C++, profiling, and co-designed pipelines."]],
    status:"Current Project",statusTitle:"H.266/VVC Tensor Compression and Compute Bypass for Generative Models",statusDesc:"This project is in the research and prototype stage. Current work covers feature-redundancy profiling, VVenC/VVdeC data adaptation, codec-parameter search, bypass operator design, and CUDA C++ integration. Results will be published after validation."}
};

export function ResearchPage({lang}:{lang:Lang}){const c=data[lang];return <SiteShell lang={lang} active="research"><PageHero kicker={c.kicker} title={c.title} description={c.desc}/><div className="page-body"><p className="research-intro">{c.intro}</p><div className="pipeline">{c.pipeline.map(([a,b],i)=><div className="pipe-step" key={a}><b>0{i+1} · {a}</b><span>{b}</span></div>)}</div><section className="research-section"><h2>{c.heading}</h2><div className="research-grid">{c.cards.map(([a,b])=><article className="research-card" key={a}><h3>{a}</h3><p>{b}</p></article>)}</div></section><section className="research-section"><div className="section-kicker">{c.status}</div><h2 style={{marginTop:12}}>{c.statusTitle}</h2><p style={{color:"var(--ink-soft)",maxWidth:820}}>{c.statusDesc}</p><div className="tag-list"><span className="tag">H.266 / VVC</span><span className="tag">VVenC / VVdeC</span><span className="tag">CUDA C++</span><span className="tag">Diffusion</span><span className="tag">Transformer</span></div></section></div></SiteShell>}
